language: php
php:
  - 5.3
  - 5.4

env:
    - DC_VERSION=2.3
    - DC_VERSION=dev-master

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar require doctrine/orm:${DC_VERSION}
  - php composer.phar install --dev

notifications:
  email:
    - lstrojny@php.net
